images and rewrites in testsite fixed
git-svn-id: https://svn.typo3.org/TYPO3v4/Extensions/install_rpm/trunk@87 735d13b6-9817-0410-8766-e36946ffe9aa

diff --git a/typo3-buildrpm b/typo3-buildrpm
--- a/typo3-buildrpm
+++ b/typo3-buildrpm
@@ -82,11 +82,25 @@ usage() {
     echo " "
 }
 
+echo "TYPO3-BuildRPM"
+echo "Dimitri Tarassenko <mitka@mitka.us>"
+echo " "
+
+# Check that we have all sources there
+if [ ! -f $BUILDDIR/src/typo3_src-$TYPOVERSION.tar.gz ] || \
+   [ ! -f $BUILDDIR/src/quickstart-$TYPOVERSION.tar.gz ] || \
+   [ ! -f $BUILDDIR/src/dummy-$TYPOVERSION.tar.gz ] || \
+   [ ! -f $BUILDDIR/src/testsite-$TYPOVERSION.tar.gz ] || \
+   [ ! -f $BUILDDIR/src/ImageMagick-4.2.9.tar.gz ]; then
+    echo "ERROR: One or more source files are missing from $BUILDDIR/src."
+    echo " "
+    cat $BUILDDIR/src/README
+    echo " "
+    usage
+    exit 1
+fi
 
 if [ -z "$1" ]; then
-    echo "TYPO3-BuildRPM"
-    echo "Dimitri Tarassenko <m1tk4@hotmail.com>"
-    echo " "
     usage
     exit 1
 fi
